name: Run test

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    step:
      - uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: action/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: 17
          cache: 'gradle'

      - name: Grant execute permissions for gradlew
        run: chmod +x gradlew

      - name: Run unit test
        run: ./gradlew clean testDebug